server: 
  port: 53010

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:53000/eureka/  

spring:
##################### DB #####################
  datasource: 
    url: jdbc:mysql://a.unisiot.com:3306/uiot_micro_oauth?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: a
    password: a


            
logging: 
  config: classpath:log4j2-dev.xml
  
swagger: 
  enable: true

apache:
  rocketmq:
    namesrvAddr: a.unisiot.com:53400
